### PR TITLE
Made ToConstant singleparam

### PR DESCRIPTION
**Pull request by TurtlePU**
Made `ToConstant` into a single-parameter class with an associated `Const` type. In correspondence with #154 and useful for simpler implementation of #222.

### CODE REVIEW

**Comment by echatav** [comment]
I'm wary of this change.

* Haskell's `toInteger :: Integral a => a -> Integer` and `toRational :: Real a => a -> Rational` that `toConstant` abstracts, the `b` type is not _determined_ by `a`.
* In an algebraic sense `toConstant` is "there is some natural or standard injection of `a` into `b`".* Fixing the types removes composability of natural injections, which have good properties.
* Adds a type family

(*which is why I renamed it `to :: Into a b => a -> b` in hierarchy proposal)

**Comment by TurtlePU** [comment]
Consider the following definition
```haskell
to' :: forall b a. (ToConstant a, FromConstant (Const a) b) => a -> b
to' = fromConstant . toConstant
```
(I was naming it `cast`, but let's call it `to'` as it is actually the same function that you consider)
* Both `to' @Integer` and `to' @Rational` can be inferred from single `ToConstant a` with `Const a ~ Integer`
* are associated types problematic? I would like to know more as I was using them here and there, maybe we would need to change these places...
* `to' @a @a = id` can be a property of `ToConstant` class

**Comment by echatav** [comment]
But then you're mixing `FromConstant` in, which is a different sort of natural morphism together with the assumed property that `to . from = id`.

In #154, the concept is that `from :: From x a => x -> a` is a natural projection onto a subset, like projection of free `Semiring Natural`, `Ring Integer` and `Field Rational` onto the sub-{semiring,ring,field} generated by 0 & 1 and that `to :: Into y a => y -> a` is as I said a natural injection. The properties are similar but because one is an algebraic projection and the other is an inclusion, they're kept separate and separately compositional.

```
-- prop> from . from = from
-- prop> from @a @a = id @a
-- prop> to . to = to
-- prop> to @a @a = id @a
-- prop > to . from = id
```

**Comment by echatav** [comment]
This conversation has been resolved ^

**Comment by TurtlePU** [comment]
@vlasin what do you think?

**Review by echatav — APPROVED** [review]
👍

**Review by vlasin — APPROVED** [review]

**Pull request merged**
